version: '3.8'

services:
    php:
        image: php:8.3-apache
        container_name: php_collection
        volumes:
            - /home/long/collection:/var/www/html
        ports:
            - "8082:80"
