version: '3.8'
services:
  php:
    image: php:8.3-apache
    container_name: php_web
    volumes:
      - ./app:/var/www/html
      - /home/long/longpham/chuong4/src:/var/www/html/src  
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0 
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db